### ISSUE TITLE
Offline reference is BROKEN

### ISSUE THREAD

**Issue by milen-prg** [processing/processing4#707]
## Description
Processing v.4.2 - Menu Help > Download Offline Reference

## Expected Behavior

Downloaded reference.zip contain BROKEN static web site, the links in index.html do not work, visually it is not correct and the files in folders manually opened are also not very useful.

I expect when the reference is downloaded, the Menu Help > Reference to work properly in offline mode. Now It not works, even I the user manually unzip the reference.zip in C:\processing-4.2\modes\java\reference folder.

## Current Behavior

Downloaded Offline Reference is BROKEN static site and not work.

## Steps to Reproduce

1. Download the Offline Reference (Menu Help)
2. Unzip the archive and text web pages inside - they are broken.

## Your Environment

 

* Processing version: 4.2
* Operating System and OS version: Windows 10 Pro 64bit
* Other information: all updated

## Possible Causes / Solutions

The prepared static site for Offline Reference is erroneously scrapped and never tested.
Please, provide the Offline Reference, your Application is used by school children frequently without Internet access, the offline documentation is vitally Important!!!

**Comment by SableRaf** [comment]
@milen-prg, I'm sorry to hear you're experiencing issues with the offline reference. However, there should be no need to manually unzip the file. Once downloaded, you should be able to access the offline reference via the `Help > Reference` option or by using the `Find in Reference` feature.

Could you please confirm if you've tried the above method? If you are still facing issues, could you provide more details about the errors you're encountering? This will allow us to better understand the problem and offer a more specific solution.

**Comment by milen-prg** [comment]
I apologize, I forget to update this issue. Before some days I delete all processing installations (folders) and download fresh archive, install libraries, etc. All works fine.
May be some problem was occurred after updating before to version 4.2. but there were installed a huge amount of extra libraries etc. (even I also was using also the version 3).
