### ISSUE TITLE
PDE doesn't launch on Raspberry Pi OS 64-bit

### ISSUE THREAD

**Issue by nickmcintyre** [processing/processing4#865]
### Most appropriate sub-area of Processing 4?

PDE

### Processing version

4.3.1

### Operating system

Raspberry Pi OS (12 bookworm)

### Steps to reproduce this

1. Click app icon (nothing happens)
2. Try to launch `./processing` from the terminal

### Additional context

The PDE fails to launch on both the Raspberry Pi 4 and 400 models. The following error message appears when running the `processing` script:

```
./processing: 110: java: not found
```

The 32-bit version seems to run just fine.

**Comment by Stefterv** [comment]
Thank you for testing, I just took a look at the build artifact, it makes sense that java was not found as it has included the macOS JDK instead of the linux arm64 JDK, we will need to fix this by altering the `build.xml` or the build actions on Github

**Comment by Stefterv** [comment]
I've made a fix and deployed a new version of 4.3.1 for linux arm64, please try it and let us know if it work! Thank you!

**Comment by nickmcintyre** [comment]
It works! Thanks @Stefterv 🙏🏽
