### ISSUE TITLE
Code signature changed?

### ISSUE THREAD

**Issue by AmnaSN** [processing/processing4#889]
### Most appropriate sub-area of Processing 4?

Other (specify if possible)

### Processing version

NA

### Operating system

MacOS

### Steps to reproduce this

"1.

2.

3."

### snippet

```processing

// Paste your code below :)

void setup() {

}

void draw() {

}
```

### Additional context

I want to confirm whether the code signature in latest mac version 4.3.1 has been changed from 'Ben Fry LLC (8SBRM6J77J)' to 'Processing Foundation, Inc. (6297K33652)'?

**Comment by SableRaf** [comment]
Hello @AmnaSN.  Starting with Processing 4.3.1, code signing is handled as a workflow step [in the CI/CD](https://github.com/processing/processing4/actions/runs/11799523595). This change is not a bug, but a normal part of the updated release workflow. Thanks for your question!
