### ISSUE TITLE
Contribution manager not loading libraries

### ISSUE THREAD

**Issue by SlimShany123** [processing/processing4#894]
### Issue description

No libraries load when i open contribution manager in processing
![image_2024-12-21_164424698](https://github.com/user-attachments/assets/5d254a67-664b-4628-b9f4-fff1a0e1f1b3)
I have looked for previous people with the same problem but cannot find a solution

### URL(s) of affected page(s)

Processing

**Comment by SableRaf** [comment]
Hello @SlimShany123 and thanks for letting us know!

We have restarted the server and the contribution manager should now correctly display the contributions.

You can monitor the status of our web services at https://processing.statuspage.io/

**Comment by SlimShany123** [comment]
Thanks, all good now
